/**
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.qvtoperational.ui.outline;

import org.eclipse.qvto.examples.xtext.qvtoperational.ui.outline.CS2ASOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class QVTOperationalOutlineTreeProvider extends CS2ASOutlineTreeProvider {
}
