/**
 * Copyright (c) 2019 Willink Transformations and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * Contributors:
 *     E.D.Willink - initial API and implementation (Bug 550053)
 *
 * This content was auto-generated by adding a Dummy class to QVTOperational.ecore and generating the models.
 * Most traces of the Dummy class were then manually deleted and the auto-generated code marked as @generated NOT.
 */
package org.eclipse.m2m.internal.qvt.oml.qvtoperational;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * @since 3.10
 * <!-- end-user-doc -->
 * @see org.eclipse.m2m.internal.qvt.oml.qvtoperational.QVTOperationalPackage
 * @generated NOT
 * @noreference This interface is not intended to be referenced by clients.
 */
public interface QVTOperationalFactory extends EFactory {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String copyright = "Copyright (c) 2007 Borland Software Corporation\r\n\r\nAll rights reserved. This program and the accompanying materials\r\nare made available under the terms of the Eclipse Public License v2.0\r\nwhich accompanies this distribution, and is available at\r\nhttp://www.eclipse.org/legal/epl-v20.html\r\n  \r\nContributors:\r\n    Borland Software Corporation - initial API and implementation"; //$NON-NLS-1$

	/**
	 * The singleton instance of the factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	QVTOperationalFactory eINSTANCE = org.eclipse.m2m.internal.qvt.oml.qvtoperational.impl.QVTOperationalFactoryImpl.init();

	/**
	 * Returns the package supported by this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the package supported by this factory.
	 * @generated
	 */
	QVTOperationalPackage getQVTOperationalPackage();

} //QVTOperationalFactory
