/**
 * generated by Xtext
 */
package org.eclipse.qvto.examples.xtext.qvtoperational.scoping;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class QVTOperationalScopeProvider /* implements org.eclipse.qvto.examples.xtext.imperativeocl.scoping.ImperativeOCLScopeProvider  */{
}
