<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtoperationalcs" nsURI="http://www.eclipse.org/qvt/pivot/1.0/QVTOperationalCS"
    nsPrefix="qvtoperationalcs">
  <eClassifiers xsi:type="ecore:EClass" name="PathName2CS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//PivotableElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPathElements2" upperBound="-1"
        eType="#//PathElement2CS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathElement2CS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//PivotableElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningPathNameCS" eType="#//PathName2CS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedTypeRef2CS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//TypedRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPathName" eType="#//PathName2CS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBinding" eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//TemplateBindingCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extentLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//RootPackageCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTypes" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//TypeCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierPropertyCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//StructuralFeatureCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStereotype" eType="#//StereotypeQualifierCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opposite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorOperationCS" eSuperTypes="#//ImperativeOperationCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationPropertyCS" eSuperTypes="#//ModulePropertyCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContextualPropertyCS" eSuperTypes="#//ModulePropertyCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInitExp" eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DirectionKindCS">
    <eLiterals name="in"/>
    <eLiterals name="out" value="1"/>
    <eLiterals name="inout" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntryOperationCS" eSuperTypes="#//ImperativeOperationCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ClassCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="HelperOperationCS" eSuperTypes="#//ImperativeOperationCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImperativeOperationCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//OperationCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedScopedName" eType="#//PathName2CS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedResults" upperBound="-1"
        eType="#//ParameterDeclarationCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBody" eType="#//OperationBodyCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImportKindCS">
    <eLiterals name="extension"/>
    <eLiterals name="access" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitPartCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initOp" eType="ecore:EEnum ../../org.eclipse.qvto.examples.xtext.imperativeocl/model/ImperativeOCLCS.ecore#//InitOpCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExp" eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingBodyCS" eSuperTypes="#//OperationBodyCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInitExps" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEndExps" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasPopulationKeyword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingCallExpCS" eSuperTypes="../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//NameExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStrict" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingOperationCS" eSuperTypes="#//ImperativeOperationCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//DirectionKindCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInheritRefs" upperBound="-1"
        eType="#//OperationRefCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDisjunctRefs" upperBound="-1"
        eType="#//OperationRefCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMergeRefs" upperBound="-1"
        eType="#//OperationRefCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRefinedRule" eType="#//PathName2CS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedWhenExps" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedWhereExps" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetamodelCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//PackageCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelKind" eType="#//MetamodelKindCS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MetamodelKindCS">
    <eLiterals name="metamodel"/>
    <eLiterals name="package" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTypeCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ClassCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="complianceKind" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral="strict"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPackageRefs" lowerBound="1"
        upperBound="-1" eType="#//PackageRefCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConditions" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTypeRefCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ParameterCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//StructuredClassCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameters" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ParameterCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedModuleUsages" upperBound="-1"
        eType="#//ModuleUsageCS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownedQualifiers" upperBound="-1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModuleKindCS">
    <eLiterals name="transformation"/>
    <eLiterals name="library" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModulePropertyCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//StructuralFeatureCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedScopedName" lowerBound="1"
        eType="#//PathName2CS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleRefCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedScopedName" lowerBound="1"
        eType="#//PathName2CS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameters" upperBound="-1"
        eType="#//ParameterDeclarationCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleUsageCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importKind" eType="#//ImportKindCS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleKind" eType="#//ModuleKindCS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedModuleRefs" lowerBound="1"
        upperBound="-1" eType="#//ModuleRefCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectExpCS" eSuperTypes="../../org.eclipse.qvto.examples.xtext.imperativeocl/model/ImperativeOCLCS.ecore#//ExpressionBlockCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedVariable" eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//VariableCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExtentRef" eType="ecore:EClass ../../org.eclipse.qvto.examples.xtext.imperativeocl/model/ImperativeOCLCS.ecore#//ExtentRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedIterator" eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//VariableCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationBodyCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//PivotableElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedContentExps" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationRefCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementRefCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPathName" lowerBound="1"
        eType="#//PathName2CS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageRefCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedScopedName" eType="#//PathName2CS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDeclarationCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ParameterCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//DirectionKindCS"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInitPart" eType="#//InitPartCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveTypeCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//DataTypeCS"/>
  <eClassifiers xsi:type="ecore:EEnum" name="QualifierKindCS">
    <eLiterals name="abstract" value="1"/>
    <eLiterals name="blackbox" value="2"/>
    <eLiterals name="static" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QVToClassCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//StructuredClassCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isIntermediate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QVToImportCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ImportCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedUnitRef" eType="#//UnitRefCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedUnitElement" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QVToLibraryCS" eSuperTypes="#//ModuleCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="QVToOperationCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//OperationCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStereotype" eType="#//StereotypeQualifierCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResolveExpCS" eSuperTypes="../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//CallExpCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDeferred" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCondition" eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTarget" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//VariableCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResolveByTypeExpCS" eSuperTypes="#//ResolveExpCS"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResolveByMappingExpCS" eSuperTypes="#//ResolveExpCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMappingRef" lowerBound="1"
        eType="#//OperationRefCS" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StereotypeQualifierCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypes" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//AnnotationCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElementPath" lowerBound="1"
        eType="#//PathName2CS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExpression" eType="ecore:EClass ../../org.eclipse.ocl.xtext.essentialocl/model/EssentialOCLCS.ecore#//ExpCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationCS" eSuperTypes="#//ModuleCS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRefinedModule" eType="#//ModuleRefCS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitRefCS" eSuperTypes="../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementCS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="segment" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLevelElements" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.ocl.xtext.base/model/BaseCS.ecore#//ElementCS"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//ModuleCS" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelTypes" upperBound="-1"
        eType="#//ModelTypeCS" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//QVToImportCS" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
</ecore:EPackage>
