/**
 * Copyright (c) 2019 Willink Transformations and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * Contributors:
 *     E.D.Willink - initial API and implementation (Bug 550053)
 *
 * This content was auto-generated by adding a Dummy class to QVTOperational.ecore and generating the models.
 * Most traces of the Dummy class were then manually deleted and the auto-generated code marked as @generated NOT.
 */
package org.eclipse.m2m.internal.qvt.oml.qvtoperational.impl;

import org.eclipse.m2m.internal.qvt.oml.qvtoperational.Dummy;

/**
 * The http://www.eclipse.org/qvt/1.0.0/Operational::Dummy class is necessary to enable EMF to auto-generate
 * the otherwise empty root package in QWVTOperational.ecore.
 *
 * This stub has been trimmed to minimize its functionality and impact and marked to inhibit re-auto-generation.
 *
 * @generated NOT
 * @noinstantiate This class is not intended to be instantiated by clients.
 */
public class DummyImpl implements Dummy {
} //DummyImpl
